import { Product } from './models/product.model';
import { User } from './models/user.model';
import bcrypt from 'bcryptjs';

export const products: Product[] = [
  {
    name: 'Sand Dune Full Rim Square',
    slug: 'sane-dune-full-rim-square',
    category: 'Computer Glass',
    image: '../assets/images/cg-1.jpeg',
    description: 'Computer Glass',
    brand: 'Sand Dune',
    price: 1200,
    countInStock: 10,
    rating: 4.5,
    numReviews: 10,
    reviews: [],
  },
  {
    name: 'Blu Hustlr Grey Rim Bold',
    slug: 'blu-hustlr-grey-rim-bold',
    category: 'Computer Glass',
    image: '../assets/images/cg-2.jpeg',
    price: 1300,
    countInStock: 20,
    brand: 'Hustlr',
    rating: 4.0,
    numReviews: 10,
    description: 'Computer Glass',
    reviews: [],
  },
  {
    name: 'Silver Full Rim Cat Eye',
    slug: 'silver-full-rim-cat-eye',
    category: 'Computer Glass',
    image: '../assets/images/cg-3.jpeg',
    price: 3200,
    countInStock: 20,
    brand: 'John Jacobs',
    rating: 4.9,
    numReviews: 29,
    description: 'Computer Glass',
    reviews: [],
  },
  {
    name: 'Blue Full Rim Cat Eye Glasses',
    slug: 'blue-full-rim-cat-eye',
    category: 'Computer Glass',
    image: '../assets/images/cg-4.jpeg',
    description: 'Computer Glass',
    brand: 'John Jacobs',
    price: 3499,
    countInStock: 16,
    rating: 4.7,
    numReviews: 12,
    reviews: [],
  },
  {
    name: 'Black Full Rim Hexagonal Glasses',
    slug: 'black-full-rim-hexagonal',
    category: 'Computer Glass',
    image: '../assets/images/cg-5.jpeg',
    description: 'Computer Glass',
    brand: 'John Jacobs',
    price: 3799,
    countInStock: 17,
    rating: 4.9,
    numReviews: 32,
    reviews: [],
  },
  {
    name: 'Blue Full Rim Rectangle Power Glass',
    slug: 'blue-full-rim-rectangle',
    category: 'Power Glass',
    image: '../assets/images/pg-1.jpeg',
    price: 2300,
    countInStock: 0,
    brand: 'Blue',
    rating: 4.8,
    numReviews: 17,
    description: 'Power Glass',
    reviews: [],
  },
  {
    name: 'Gunmetal Black Full Rim Round Glass',
    slug: 'gunmetal-black-full-rim-square',
    category: 'Power Glass',
    image: '../assets/images/pg-2.jpeg',
    price: 1400,
    countInStock: 15,
    brand: 'Gunmetal',
    rating: 4.5,
    numReviews: 14,
    description: 'Power Glass',
    reviews: [],
  },
  {
    name: 'Pink Full Rim Round Eyeglasses',
    slug: 'pinl-full-rim-round',
    category: 'Power Glass',
    image: '../assets/images/pg-3.jpeg',
    price: 3200,
    countInStock: 17,
    brand: 'John Jacobs',
    rating: 4.4,
    numReviews: 13,
    description: 'Power Glass',
    reviews: [],
  },
  {
    name: 'Pro Rimless Rectangle Eyeglasses',
    slug: 'pro-rimless-rectangle',
    category: 'Power Glass',
    image: '../assets/images/pg-4.jpeg',
    price: 4200,
    countInStock: 21,
    brand: 'John Jacobs',
    rating: 4.8,
    numReviews: 23,
    description: 'Power Glass',
    reviews: [],
  },
  {
    name: 'Grey Rimless Rectangle Eyeglasses',
    slug: 'grey-rimless-rectangle',
    category: 'Power Glass',
    image: '../assets/images/pg-5.jpeg',
    price: 3200,
    countInStock: 15,
    brand: 'Ray-Ban',
    rating: 4.5,
    numReviews: 15,
    description: 'Power Glass',
    reviews: [],
  },
  {
    name: 'Black Full Rim Vincent Chase',
    slug: 'black-full-rim-vc',
    category: 'Sunglass',
    image: '../assets/images/sg-1.jpeg',
    price: 1300,
    countInStock: 12,
    brand: 'Vincent Chase',
    rating: 4.5,
    numReviews: 15,
    description: 'Sunglass',
    reviews: [],
  },
  {
    name: 'Green Full Rim Vincent Chase',
    slug: 'green-full-rim-vc',
    category: 'Sunglass',
    image: '../assets/images/sg-2.jpeg',
    price: 1300,
    countInStock: 12,
    brand: 'Vincent Chase',
    rating: 4.5,
    numReviews: 15,
    description: 'Sunglass',
    reviews: [],
  },
  {
    name: 'Gold Full Rim Aviator Sunglasses',
    slug: 'gold-full-rim-avi',
    category: 'Sunglass',
    image: '../assets/images/sg-3.jpeg',
    price: 1499,
    countInStock: 28,
    brand: 'Vincent Chase',
    rating: 4.4,
    numReviews: 9,
    description: 'Sunglass',
    reviews: [],
  },
  {
    name: 'Black Full Rim Wayfarer Sunglasses',
    slug: 'black-full-rim-wayfarer',
    category: 'Sunglass',
    image: '../assets/images/sg-4.jpeg',
    price: 1299,
    countInStock: 18,
    brand: 'Vincent Chase',
    rating: 4.7,
    numReviews: 12,
    description: 'Sunglass',
    reviews: [],
  },
  {
    name: 'Zebra Full Rim Wayfarer Sunglasses',
    slug: 'zebra-full-rim-wayfarer',
    category: 'Sunglass',
    image: '../assets/images/sg-5.jpeg',
    price: 1599,
    countInStock: 18,
    brand: 'Vincent Chase Polarized',
    rating: 4.8,
    numReviews: 19,
    description: 'Polarized Sunglass',
    reviews: [],
  },
  {
    name: 'Yellow Full Rim Sports Sunglasses',
    slug: 'yellow-full-rim-sports',
    category: 'Sunglass',
    image: '../assets/images/sg-6.jpeg',
    price: 4200,
    countInStock: 17,
    brand: 'New Balance',
    rating: 4.8,
    numReviews: 15,
    description: 'Polarized Sunglass',
    reviews: [],
  },
];

export const users: User[] = [
  {
    name: 'Admin',
    email: 'admin@admin',
    password: bcrypt.hashSync('admin'),
    isAdmin: true,
  },
  {
    name: 'user',
    email: 'user@user',
    password: bcrypt.hashSync('user'),
    isAdmin: false,
  },
  {
    name: 'harrish',
    email: 'harrish@gmail.com',
    password: bcrypt.hashSync('123456'),
    isAdmin: false,
  },
];
